# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.23)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS LLVMHello LLVMTestingSupport FileCheck llvm-PerfectShuffle count not UnicodeNameMappingGenerator yaml-bench BugpointPasses lli-child-target llvm-jitlink-executor obj2yaml yaml2obj Bye TestPlugin DoublerPlugin llvm_gtest llvm_gtest_main)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target LLVMHello
add_library(LLVMHello MODULE IMPORTED)

# Create imported target LLVMTestingSupport
add_library(LLVMTestingSupport STATIC IMPORTED)

set_target_properties(LLVMTestingSupport PROPERTIES
  INTERFACE_LINK_LIBRARIES "LLVMSupport;\$<LINK_ONLY:llvm_gtest>"
)

# Create imported target FileCheck
add_executable(FileCheck IMPORTED)

# Create imported target llvm-PerfectShuffle
add_executable(llvm-PerfectShuffle IMPORTED)

# Create imported target count
add_executable(count IMPORTED)

# Create imported target not
add_executable(not IMPORTED)

# Create imported target UnicodeNameMappingGenerator
add_executable(UnicodeNameMappingGenerator IMPORTED)

# Create imported target yaml-bench
add_executable(yaml-bench IMPORTED)

# Create imported target BugpointPasses
add_library(BugpointPasses MODULE IMPORTED)

# Create imported target lli-child-target
add_executable(lli-child-target IMPORTED)
set_property(TARGET lli-child-target PROPERTY ENABLE_EXPORTS 1)

# Create imported target llvm-jitlink-executor
add_executable(llvm-jitlink-executor IMPORTED)
set_property(TARGET llvm-jitlink-executor PROPERTY ENABLE_EXPORTS 1)

# Create imported target obj2yaml
add_executable(obj2yaml IMPORTED)

# Create imported target yaml2obj
add_executable(yaml2obj IMPORTED)

# Create imported target Bye
add_library(Bye MODULE IMPORTED)

# Create imported target TestPlugin
add_library(TestPlugin MODULE IMPORTED)

# Create imported target DoublerPlugin
add_library(DoublerPlugin MODULE IMPORTED)

# Create imported target llvm_gtest
add_library(llvm_gtest STATIC IMPORTED)

set_target_properties(llvm_gtest PROPERTIES
  INTERFACE_COMPILE_OPTIONS "-Wno-suggest-override"
  INTERFACE_INCLUDE_DIRECTORIES "/home/pegasus/Documents/LLVM_Rust/CCR-master/llvm/utils/unittest/googletest/include;/home/pegasus/Documents/LLVM_Rust/CCR-master/llvm/utils/unittest/googlemock/include"
  INTERFACE_LINK_LIBRARIES "pthread;LLVMSupport"
)

# Create imported target llvm_gtest_main
add_library(llvm_gtest_main STATIC IMPORTED)

set_target_properties(llvm_gtest_main PROPERTIES
  INTERFACE_LINK_LIBRARIES "llvm_gtest;LLVMSupport"
)

# Import target "LLVMHello" for configuration "Debug"
set_property(TARGET LLVMHello APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(LLVMHello PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_DEBUG ""
  IMPORTED_LOCATION_DEBUG "/home/pegasus/Documents/LLVM_Rust/CCR-master/llvm/mybuilddir/lib/LLVMHello.so"
  IMPORTED_NO_SONAME_DEBUG "TRUE"
  )

# Import target "LLVMTestingSupport" for configuration "Debug"
set_property(TARGET LLVMTestingSupport APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(LLVMTestingSupport PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/pegasus/Documents/LLVM_Rust/CCR-master/llvm/mybuilddir/lib/libLLVMTestingSupport.a"
  )

# Import target "FileCheck" for configuration "Debug"
set_property(TARGET FileCheck APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(FileCheck PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/pegasus/Documents/LLVM_Rust/CCR-master/llvm/mybuilddir/bin/FileCheck"
  )

# Import target "llvm-PerfectShuffle" for configuration "Debug"
set_property(TARGET llvm-PerfectShuffle APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(llvm-PerfectShuffle PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/pegasus/Documents/LLVM_Rust/CCR-master/llvm/mybuilddir/bin/llvm-PerfectShuffle"
  )

# Import target "count" for configuration "Debug"
set_property(TARGET count APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(count PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/pegasus/Documents/LLVM_Rust/CCR-master/llvm/mybuilddir/bin/count"
  )

# Import target "not" for configuration "Debug"
set_property(TARGET not APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(not PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/pegasus/Documents/LLVM_Rust/CCR-master/llvm/mybuilddir/bin/not"
  )

# Import target "UnicodeNameMappingGenerator" for configuration "Debug"
set_property(TARGET UnicodeNameMappingGenerator APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(UnicodeNameMappingGenerator PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/pegasus/Documents/LLVM_Rust/CCR-master/llvm/mybuilddir/bin/UnicodeNameMappingGenerator"
  )

# Import target "yaml-bench" for configuration "Debug"
set_property(TARGET yaml-bench APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(yaml-bench PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/pegasus/Documents/LLVM_Rust/CCR-master/llvm/mybuilddir/bin/yaml-bench"
  )

# Import target "BugpointPasses" for configuration "Debug"
set_property(TARGET BugpointPasses APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(BugpointPasses PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_DEBUG ""
  IMPORTED_LOCATION_DEBUG "/home/pegasus/Documents/LLVM_Rust/CCR-master/llvm/mybuilddir/lib/BugpointPasses.so"
  IMPORTED_NO_SONAME_DEBUG "TRUE"
  )

# Import target "lli-child-target" for configuration "Debug"
set_property(TARGET lli-child-target APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(lli-child-target PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/pegasus/Documents/LLVM_Rust/CCR-master/llvm/mybuilddir/bin/lli-child-target"
  )

# Import target "llvm-jitlink-executor" for configuration "Debug"
set_property(TARGET llvm-jitlink-executor APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(llvm-jitlink-executor PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/pegasus/Documents/LLVM_Rust/CCR-master/llvm/mybuilddir/bin/llvm-jitlink-executor"
  )

# Import target "obj2yaml" for configuration "Debug"
set_property(TARGET obj2yaml APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(obj2yaml PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/pegasus/Documents/LLVM_Rust/CCR-master/llvm/mybuilddir/bin/obj2yaml"
  )

# Import target "yaml2obj" for configuration "Debug"
set_property(TARGET yaml2obj APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(yaml2obj PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/pegasus/Documents/LLVM_Rust/CCR-master/llvm/mybuilddir/bin/yaml2obj"
  )

# Import target "Bye" for configuration "Debug"
set_property(TARGET Bye APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Bye PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_DEBUG ""
  IMPORTED_LOCATION_DEBUG "/home/pegasus/Documents/LLVM_Rust/CCR-master/llvm/mybuilddir/lib/Bye.so"
  IMPORTED_NO_SONAME_DEBUG "TRUE"
  )

# Import target "TestPlugin" for configuration "Debug"
set_property(TARGET TestPlugin APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TestPlugin PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_DEBUG ""
  IMPORTED_LOCATION_DEBUG "/home/pegasus/Documents/LLVM_Rust/CCR-master/llvm/mybuilddir/unittests/Passes/TestPlugin.so"
  IMPORTED_NO_SONAME_DEBUG "TRUE"
  )

# Import target "DoublerPlugin" for configuration "Debug"
set_property(TARGET DoublerPlugin APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DoublerPlugin PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_DEBUG ""
  IMPORTED_LOCATION_DEBUG "/home/pegasus/Documents/LLVM_Rust/CCR-master/llvm/mybuilddir/unittests/Passes/DoublerPlugin.so"
  IMPORTED_NO_SONAME_DEBUG "TRUE"
  )

# Import target "llvm_gtest" for configuration "Debug"
set_property(TARGET llvm_gtest APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(llvm_gtest PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/pegasus/Documents/LLVM_Rust/CCR-master/llvm/mybuilddir/lib/libllvm_gtest.a"
  )

# Import target "llvm_gtest_main" for configuration "Debug"
set_property(TARGET llvm_gtest_main APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(llvm_gtest_main PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/pegasus/Documents/LLVM_Rust/CCR-master/llvm/mybuilddir/lib/libllvm_gtest_main.a"
  )

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "LLVMSupport" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
